import { Metadata } from "next";
import PostList from "../../components/PostList";
import PostSearch from "../../components/PostSearch";

export const metadata: Metadata = {
  title: "Posts | Next 13 App",
  description: "Generated by create next app",
};

const Posts = () => {
  return (
    <>
      <h2>Posts page</h2>
      <PostSearch />
      <PostList />
    </>
  );
};

export default Posts;
