import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Blog | Next 13 App',
  description: 'Generated by create next app',
}

const Blog = () => {
  return (
    <h2>
      Blog page
    </h2>
  );
};

export default Blog;