import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'About | Next 13 App',
  description: 'Generated by create next app',
}

const About = () => {
  return (
    <h2>
      About page
    </h2>
  );
};

export default About;