import './globals.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'

const inter = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next 13 App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='container'>
        <Header />
        {children}
        <Footer />
        </main>
      </body>
    </html>
  )
}
